package com.ddk.smmp.adapter.webservice.server;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.8 2014-07-10T15:26:57.793+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "smsi", wsdlLocation = "smsi.wsdl", targetNamespace = "http://www.sioo.cn/smsi/")
public class Smsi_Service extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://www.sioo.cn/smsi/", "smsi");
	public final static QName SmsiSOAP = new QName("http://www.sioo.cn/smsi/", "smsiSOAP");
	
	static {
		URL url = Smsi_Service.class.getResource("smsi.wsdl");
		if (url == null) {
			url = Smsi_Service.class.getClassLoader().getResource("smsi.wsdl");
		}
		if (url == null) {
			java.util.logging.Logger.getLogger(Smsi_Service.class.getName()).log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}", "smsi.wsdl");
		}
		WSDL_LOCATION = url;
	}

	public Smsi_Service(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public Smsi_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Smsi_Service() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns Smsi
	 */
	@WebEndpoint(name = "smsiSOAP")
	public Smsi getSmsiSOAP() {
		return super.getPort(SmsiSOAP, Smsi.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns Smsi
	 */
	@WebEndpoint(name = "smsiSOAP")
	public Smsi getSmsiSOAP(WebServiceFeature... features) {
		return super.getPort(SmsiSOAP, Smsi.class, features);
	}
}