package com.ddk.smmp.adapter.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8 2014-07-10T15:26:57.781+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://www.sioo.cn/smsi/", name = "smsi")
@XmlSeeAlso({ ObjectFactory.class })
public interface Smsi {

	@WebResult(name = "result", targetNamespace = "")
	@RequestWrapper(localName = "invoke", targetNamespace = "http://www.sioo.cn/smsi/", className = "com.ddk.smmp.adapter.webservice.server.Invoke")
	@WebMethod(action = "http://www.sioo.cn/smsi/invoke")
	@ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://www.sioo.cn/smsi/", className = "com.ddk.smmp.adapter.webservice.server.InvokeResponse")
	public java.lang.String invoke (
			@WebParam(name = "commandId", targetNamespace = "") int commandId,
			@WebParam(name = "uId", targetNamespace = "") java.lang.String uId,
			@WebParam(name = "body", targetNamespace = "") java.lang.String body) throws Exception;
}
