package com.ddk.smmp.adapter.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.8 2014-07-10T16:11:55.094+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "SmsiService", wsdlLocation = "http://127.0.0.1:8080/sioo?wsdl", targetNamespace = "http://www.sioo.cn/smsi/")
public class SmsiService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://www.sioo.cn/smsi/", "SmsiService");
	public final static QName SmsiPort = new QName("http://www.sioo.cn/smsi/", "smsiPort");
	static {
		URL url = null;
		try {
			url = new URL("http://192.168.0.114:7003/sioo?wsdl");
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(SmsiService.class.getName())
					.log(java.util.logging.Level.INFO,
							"Can not initialize the default wsdl from {0}",
							"http://127.0.0.1:8080/sioo?wsdl");
		}
		WSDL_LOCATION = url;
	}

	public SmsiService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public SmsiService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SmsiService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns Smsi
	 */
	@WebEndpoint(name = "smsiPort")
	public Smsi getSmsiPort() {
		return super.getPort(SmsiPort, Smsi.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns Smsi
	 */
	@WebEndpoint(name = "smsiPort")
	public Smsi getSmsiPort(WebServiceFeature... features) {
		return super.getPort(SmsiPort, Smsi.class, features);
	}
}